name: Auto triggered workflow

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  Windows:
    name: build-windows
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
        
      - name: Installing vcpkg (windows)
        shell: cmd
        run: |
          cd ..
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          git checkout --force 2020.01
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install cppzmq:x64-windows

      - name: Before build
        run: |  
          cd ${{github.workspace }}
          mkdir _build
          cd _build
          rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
          
      - name: Running cmake(windows)
        shell: cmd
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -Dgtest_disable_pthreads=ON ..
          cmake --build . --config Release
