name: CMake

on: 
  push:
    branches: 
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2    

    - name: Build
      working-directory: ${{github.workspace}}
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        mkdir _build
        cd _build
        cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Dgtest_disable_pthreads=ON ..
        cmake --build . --config Release

    - name: Test
      timeout-minutes: 15
      shell: bash
      working-directory: ${{github.workspace}}\test
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ../_build/test/runTests.exe
