name: CMake

on: 
  push:
    branches: 
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2016
    strategy:
     matrix:
         include:
             - compiler: "msvc15"
               generator: "Visual Studio 14 2015"
             - compiler: "MinGW"
               generator: "MinGW Makefiles"
    
    steps:
    - uses: actions/checkout@v2    

    - name: Build with matrix.generator
      shell: bash
      env: 
        GENERATOR: ${{matrix.generator}}
      working-directory: ${{github.workspace}}
      run: |
        mkdir _build
        cd _build
        cmake -G " $GENERATOR " -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Dgtest_disable_pthreads=ON ..
        cmake --build . --config $BUILD_TYPE

    - if: matrix.compiler == 'MinGW'
      name: Test with MinGW
      timeout-minutes: 15
      shell: bash
      working-directory: ${{github.workspace}}\test
      run: ../_build/test/runTests.exe

    - if: matrix.compiler == 'msvc15'
      name: Test with MSVC15
      timeout-minutes: 15
      shell: bash
      working-directory: ${{github.workspace}}\test
      run: ../_build/test/$BUILD_TYPE/runTests.exe
